-- MySQL Script generated by MySQL Workbench
-- 03/23/17 20:43:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema consumidoronlinetcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema consumidoronlinetcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `consumidoronlinetcc` DEFAULT CHARACTER SET utf8 ;
USE `consumidoronlinetcc` ;

-- -----------------------------------------------------
-- Table `consumidoronlinetcc`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidoronlinetcc`.`cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `login` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login` (`login` ASC),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consumidoronlinetcc`.`itempesquisa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidoronlinetcc`.`itempesquisa` (
  `id_pesquisa` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `nome_pesquisa` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pesquisa`),
  INDEX `id_cliente` (`id_cliente` ASC),
  CONSTRAINT `itempesquisa_ibfk_1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `consumidoronlinetcc`.`cliente` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consumidoronlinetcc`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidoronlinetcc`.`tag` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome_tag` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 75
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consumidoronlinetcc`.`pesquisa_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidoronlinetcc`.`pesquisa_tag` (
  `id_pesquisa` INT(11) NOT NULL,
  `id_tag` INT(11) NOT NULL,
  INDEX `id_pesquisa` (`id_pesquisa` ASC),
  INDEX `id_tag` (`id_tag` ASC),
  CONSTRAINT `pesquisa_tag_ibfk_1`
    FOREIGN KEY (`id_pesquisa`)
    REFERENCES `consumidoronlinetcc`.`itempesquisa` (`id_pesquisa`),
  CONSTRAINT `pesquisa_tag_ibfk_2`
    FOREIGN KEY (`id_tag`)
    REFERENCES `consumidoronlinetcc`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consumidoronlinetcc`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidoronlinetcc`.`produto` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `consumidoronlinetcc`.`produto_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `consumidoronlinetcc`.`produto_tag` (
  `id_produto` INT(11) NOT NULL,
  `id_tag` INT(11) NOT NULL,
  INDEX `id_produto` (`id_produto` ASC),
  INDEX `id_tag` (`id_tag` ASC),
  CONSTRAINT `produto_tag_ibfk_1`
    FOREIGN KEY (`id_produto`)
    REFERENCES `consumidoronlinetcc`.`produto` (`id`),
  CONSTRAINT `produto_tag_ibfk_2`
    FOREIGN KEY (`id_tag`)
    REFERENCES `consumidoronlinetcc`.`tag` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
