/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Conexao.Conexao;
import DAO.ClienteDAO;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius Alves
 */
public class jFLogin extends javax.swing.JFrame {

    /**
     * Creates new form jFLogin
     */
    public jFLogin() {
        initComponents();

        jLBPlanoFundo.setBounds(0, 0, 400, 300);

        ImageIcon img = new ImageIcon(jFLogin.class.getResource("/IMG/img.jpg"));
        Image imagem = img.getImage().getScaledInstance(jLBPlanoFundo.getWidth(), jLBPlanoFundo.getHeight(), Image.SCALE_SMOOTH);

        jLBPlanoFundo.setIcon(new ImageIcon(imagem));

    }

    public void chamarPrincipal(String login) {
        jFPrincipal pri = new jFPrincipal(login);
        pri.setVisible(true);
    }

    public void chamarCadastrar() {
        jFCadastrar cadastrar = new jFCadastrar();
        cadastrar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBLogin = new javax.swing.JLabel();
        jLBSenha = new javax.swing.JLabel();
        jTFLogin = new javax.swing.JTextField();
        jPFSenha = new javax.swing.JPasswordField();
        jLBTitulo = new javax.swing.JLabel();
        jBTNEntrar = new javax.swing.JButton();
        jBTNCriarConta = new javax.swing.JButton();
        jBTNSair = new javax.swing.JButton();
        jLBPlanoFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBLogin.setText("LOGIN");
        getContentPane().add(jLBLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLBSenha.setText("SENHA");
        getContentPane().add(jLBSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jTFLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray));
        jTFLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFLoginKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFLoginKeyTyped(evt);
            }
        });
        getContentPane().add(jTFLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 320, -1));

        jPFSenha.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray));
        jPFSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPFSenhaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPFSenhaKeyTyped(evt);
            }
        });
        getContentPane().add(jPFSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 320, -1));

        jLBTitulo.setText("FAZER LOGIN");
        getContentPane().add(jLBTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jBTNEntrar.setText("ENTRAR");
        jBTNEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray));
        jBTNEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jBTNEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));

        jBTNCriarConta.setText("CRIAR CONTA");
        jBTNCriarConta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray));
        jBTNCriarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNCriarContaActionPerformed(evt);
            }
        });
        getContentPane().add(jBTNCriarConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 170, -1));

        jBTNSair.setText("SAIR");
        jBTNSair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.darkGray));
        jBTNSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBTNSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 170, -1));
        getContentPane().add(jLBPlanoFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBTNSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNSairActionPerformed

        System.exit(0);


    }//GEN-LAST:event_jBTNSairActionPerformed

    private void jBTNEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNEntrarActionPerformed
 
        
        /*   jFPrincipal pri = new jFPrincipal();
         pri.getJMenuBar().
         DefaultTableModel dtmCliente; 
         */
        ClienteDAO cd = new ClienteDAO();
        String senha = "";
        String login = jTFLogin.getText();
        
        

        char[] pass = jPFSenha.getPassword();
        for (int i = 0; i < pass.length; i++) {
            senha += pass[i];
        }
        cd.checkLogin(login, senha);
        if ((jTFLogin.getText().equals(""))
                || (senha.equals(""))) {
        }
        if (cd.checkLogin(login, senha)) {
            
            chamarPrincipal(login);
            cd.ler(login);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Login ou senha invalido");
        }
    }//GEN-LAST:event_jBTNEntrarActionPerformed

    private void jBTNCriarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNCriarContaActionPerformed

        jTFLogin.setText("");
        jPFSenha.setText("");
        chamarCadastrar();

    }//GEN-LAST:event_jBTNCriarContaActionPerformed

    private void jTFLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFLoginKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTFLoginKeyTyped

    private void jPFSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFSenhaKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPFSenhaKeyTyped

    private void jTFLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFLoginKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){        
       jBTNEntrar.doClick();
            
            
            
        }
    }//GEN-LAST:event_jTFLoginKeyPressed

    private void jPFSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPFSenhaKeyPressed
       
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){        
       jBTNEntrar.doClick();
            
            
            
        }
        
    }//GEN-LAST:event_jPFSenhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNCriarConta;
    private javax.swing.JButton jBTNEntrar;
    private javax.swing.JButton jBTNSair;
    private javax.swing.JLabel jLBLogin;
    private javax.swing.JLabel jLBPlanoFundo;
    private javax.swing.JLabel jLBSenha;
    private javax.swing.JLabel jLBTitulo;
    private javax.swing.JPasswordField jPFSenha;
    private javax.swing.JTextField jTFLogin;
    // End of variables declaration//GEN-END:variables
}
