/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import DAO.ClienteDAO;
import DAO.ProdutoDAO;
import Modelo.ClienteModelo;
import Modelo.ProdutoModelo;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vinicius Alves
 */
public class jFPrincipal extends javax.swing.JFrame {

    String login;
    Integer idLogin;

    public jFPrincipal(String login) {
        initComponents();
        this.login = login;
        DefaultTableModel dtmCliente = (DefaultTableModel) jTPrincipal.getModel();
        jTPrincipal.setRowSorter(new TableRowSorter(dtmCliente));
        DefaultTableModel dtmProduto = (DefaultTableModel) jTProduto.getModel();
        ProdutoDAO pd = new ProdutoDAO();
        readJTableP();
        readJTable();
    }

    public void chamarLogin() {
        jFLogin fLogin = new jFLogin();
        fLogin.setVisible(true);
        dispose();
    }

    public void readJTable() {
        DefaultTableModel dtmCliente = (DefaultTableModel) jTPrincipal.getModel();
        ClienteDAO cd = new ClienteDAO();

        for (ClienteModelo c : cd.ler(login)) {
            
            this.idLogin = c.getId();
            
            dtmCliente.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getEmail(),
                c.getCpf(),
                c.getRg(),
                c.getData_nasc(),
                c.getLogin(),
                c.getSenha()
            });
        }
    }
    
     public void readJTableP() {
        DefaultTableModel dtmProduto = (DefaultTableModel) jTProduto.getModel();
        dtmProduto.setNumRows(0);
        ProdutoDAO pd = new ProdutoDAO();

        for (ProdutoModelo pm : pd.ler(login)) {
            dtmProduto.addRow(new Object[]{
                pm.getId_prod(),
                pm.getNome(),
                pm.getPreco()
            });
        }
    }
    

    public void chamarAtualizar() {
        jFAtualizar at = new jFAtualizar(login);
        at.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPrincipal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTFNomeP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBTNSalvar = new javax.swing.JButton();
        jBTNCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTProduto = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jFPPreco = new javax.swing.JTextField();
        jMBPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMPrincipal = new javax.swing.JMenu();
        jMDadosConta = new javax.swing.JMenuItem();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        jTPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "EMAIL", "CPF", "RG", "DATA_NASC", "LOGIN", "SENHA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTPrincipal);

        jLabel1.setText("Cadastrar Item");

        jTFNomeP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNomePKeyPressed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("Preço");

        jBTNSalvar.setText("Salvar");
        jBTNSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNSalvarActionPerformed(evt);
            }
        });

        jBTNCancelar.setText("Cancelar");
        jBTNCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTNCancelarActionPerformed(evt);
            }
        });

        jTProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "PRECO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTProduto);

        jFPPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFPPrecoActionPerformed(evt);
            }
        });
        jFPPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jFPPrecoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFPPrecoKeyTyped(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenu1.setPreferredSize(new java.awt.Dimension(50, 20));
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Deslogar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMBPrincipal.add(jMenu1);

        jMPrincipal.setText("Atualizar");

        jMDadosConta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMDadosConta.setText("Dados da Conta");
        jMDadosConta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMDadosContaMouseClicked(evt);
            }
        });
        jMDadosConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMDadosContaActionPerformed(evt);
            }
        });
        jMPrincipal.add(jMDadosConta);

        jMBPrincipal.add(jMPrincipal);

        setJMenuBar(jMBPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBTNSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jBTNCancelar)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(89, 89, 89)
                                    .addComponent(jLabel1)
                                    .addGap(104, 104, 104))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(jTFNomeP)
                                    .addComponent(jLabel3)
                                    .addComponent(jFPPreco, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFNomeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jFPPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBTNCancelar)
                            .addComponent(jBTNSalvar))
                        .addGap(41, 41, 41)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
        );

        setSize(new java.awt.Dimension(916, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked


    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        chamarLogin();
        this.dispose();

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        System.exit(0);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMDadosContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMDadosContaActionPerformed
        chamarAtualizar();
        this.dispose();
    }//GEN-LAST:event_jMDadosContaActionPerformed

    private void jMDadosContaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMDadosContaMouseClicked
        this.dispose();
        chamarAtualizar();

    }//GEN-LAST:event_jMDadosContaMouseClicked

    private void jBTNSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNSalvarActionPerformed
       
        boolean ok = true;
        String nome = jTFNomeP.getText();
        String nomeU = nome.toUpperCase();
        

        if (jTFNomeP.getText().equals("")
         ||(jFPPreco.getText().equals(""))){
            JOptionPane.showMessageDialog(null, "Campo em branco");
            ok = false;
        } else {
        
        if (ok == true){
        Double preco = Double.parseDouble(jFPPreco.getText());
            ProdutoDAO pd = new ProdutoDAO();
        ProdutoModelo pm = new ProdutoModelo();
        pm.setNome(nomeU);
        pm.setId(idLogin);
        pm.setPreco(preco);
        pd.criar(pm);
        readJTableP();
        }
        }
    }//GEN-LAST:event_jBTNSalvarActionPerformed

    private void jBTNCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNCancelarActionPerformed
        
        jTFNomeP.setText("");
        jFPPreco.setText("");
        
        
    }//GEN-LAST:event_jBTNCancelarActionPerformed

    private void jFPPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFPPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFPPrecoActionPerformed

    private void jFPPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFPPrecoKeyPressed
if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
   jBTNSalvar.doClick();
       }        
        
    }//GEN-LAST:event_jFPPrecoKeyPressed

    private void jTFNomePKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNomePKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
       jBTNSalvar.doClick();
       }
    }//GEN-LAST:event_jTFNomePKeyPressed

    private void jFPPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFPPrecoKeyTyped
         char c = evt.getKeyChar();

        if (c < '0' || c > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_jFPPrecoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
         new jFPrincipal().setVisible(true);
         }
         });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTNCancelar;
    private javax.swing.JButton jBTNSalvar;
    private javax.swing.JTextField jFPPreco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMBPrincipal;
    private javax.swing.JMenuItem jMDadosConta;
    private javax.swing.JMenu jMPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFNomeP;
    private javax.swing.JTable jTPrincipal;
    private javax.swing.JTable jTProduto;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
