/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Vinicius Alves
 */
public class jFSplash extends javax.swing.JFrame {

    /**
     * Creates new form jFSplash
     */
    public jFSplash() {
        initComponents();

        new Thread() {

            public void run() {
               
                jLBPlanoFundo.setBounds(0, 0, 470, 350);
                
                ImageIcon img = new ImageIcon(jFSplash.class.getResource("/IMG/images.jpg"));
                Image imagem = img.getImage().getScaledInstance(jLBPlanoFundo.getWidth(), jLBPlanoFundo.getHeight(), Image.SCALE_SMOOTH);
                
                jLBPlanoFundo.setIcon(new ImageIcon(imagem));
                for (int i = 0; i < 101; i++) {
                    try {

                        sleep(60);
                        jBarra.setValue(i);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(jFSplash.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    if (jBarra.getValue() == 0) {
                        jLBDadosCarregar.setText("Banco de dados");
                    }
                    if (jBarra.getValue() >= 50) {
                        jLBDadosCarregar.setText("Interface Grafica");
                    }
                    if (jBarra.getValue() >= 100) {
                        jFLogin fLogin = new jFLogin();
                        fLogin.setVisible(true);
                        dispose();
                    }
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBarra = new javax.swing.JProgressBar();
        jLBTitulo = new javax.swing.JLabel();
        jLBCarregar = new javax.swing.JLabel();
        jLBDadosCarregar = new javax.swing.JLabel();
        jLBDesenvolvido = new javax.swing.JLabel();
        jLBAutor = new javax.swing.JLabel();
        jLBPlanoFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(466, 348));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jBarra.setFont(new java.awt.Font("Arial Narrow", 1, 10)); // NOI18N
        jBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), java.awt.Color.darkGray));
        jBarra.setStringPainted(true);
        getContentPane().add(jBarra);
        jBarra.setBounds(60, 130, 340, 20);

        jLBTitulo.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLBTitulo.setText("Cadastro.JAVA");
        getContentPane().add(jLBTitulo);
        jLBTitulo.setBounds(50, 20, 360, 56);

        jLBCarregar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLBCarregar.setText("Carregando");
        getContentPane().add(jLBCarregar);
        jLBCarregar.setBounds(170, 100, 110, 22);

        jLBDadosCarregar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLBDadosCarregar.setText("Exemplo");
        getContentPane().add(jLBDadosCarregar);
        jLBDadosCarregar.setBounds(170, 160, 230, 22);

        jLBDesenvolvido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLBDesenvolvido.setText("Desenvolvido por");
        getContentPane().add(jLBDesenvolvido);
        jLBDesenvolvido.setBounds(160, 220, 155, 22);

        jLBAutor.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLBAutor.setText("Vinicius Alves Patricio");
        getContentPane().add(jLBAutor);
        jLBAutor.setBounds(150, 250, 190, 22);
        getContentPane().add(jLBPlanoFundo);
        jLBPlanoFundo.setBounds(0, 0, 470, 350);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFSplash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFSplash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jBarra;
    private javax.swing.JLabel jLBAutor;
    private javax.swing.JLabel jLBCarregar;
    private javax.swing.JLabel jLBDadosCarregar;
    private javax.swing.JLabel jLBDesenvolvido;
    private javax.swing.JLabel jLBPlanoFundo;
    private javax.swing.JLabel jLBTitulo;
    // End of variables declaration//GEN-END:variables
}
