/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Auxiliar.EnviarEmail;
import DAO.ClienteDAO;
import ModeloTabela.Cliente;
import com.sun.mail.util.MailConnectException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.SQLException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Vinicius Alves
 */
public class JF_AlterarInfoConta extends javax.swing.JFrame {

    /**
     * Creates new form JF_AlterarInfoConta
     */
    String nome, senha, email, login, emailOk, loginOK = null;

    int id = 0;

    public JF_AlterarInfoConta(String nome, String login, String senha, String email, int id) throws SQLException {
        initComponents();

        URL caminhoIcone = getClass().getResource("/IMG/IconeCO7.PNG");
        Image iconeTitile = Toolkit.getDefaultToolkit().getImage(caminhoIcone);
        this.setIconImage(iconeTitile);
        this.nome = nome;
        this.senha = senha;
        this.email = email;
        this.login = login;
        this.id = id;
        this.loginOK = this.login;
        this.emailOk = this.email;
        info();
        retornaTudoCertinho();

    }

    public void info() {
        JTF_Nome.setText(this.nome);
        JTF_Email.setText(this.email);
        JTF_ConfirmaEmail.setText(this.email);
        JTF_Login.setText(this.login);
        JTF_Senha.setText(this.senha);
        JTF_ConfirmaSenha.setText(this.senha);

    }

    public void retornaTudoCertinho() throws SQLException {
        ClienteDAO cd = new ClienteDAO();
        cd.recolheinfo(this.id);

        JTF_Nome.setText(cd.recolheinfo(this.id).getNome());
        JTF_Email.setText(cd.recolheinfo(this.id).getEmail());
        JTF_ConfirmaEmail.setText(cd.recolheinfo(this.id).getEmail());
        JTF_Login.setText(cd.recolheinfo(this.id).getLogin());
        JTF_Senha.setText(cd.recolheinfo(this.id).getSenha());
        JTF_ConfirmaSenha.setText(cd.recolheinfo(this.id).getSenha());

    }

    public boolean checkMudou(String nome, String login, String email, String email2, String senha, String senha2) {
        if (this.nome.equals(nome)) {

            if (this.login.equals(login)) {
                if (this.email.equals(email)) {
                    if (this.email.equals(email2)) {
                        if (this.senha.equals(senha)) {
                            if (this.senha.equals(senha2)) {
                                return true;
                            } else {
                                return false;
                            }
                        } else {
                            return false;
                        }
                    } else {
                        return false;
                    }
                } else {
                    return false;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JTF_Nome = new javax.swing.JTextField();
        JTF_Email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTF_ConfirmaEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTF_Login = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTF_Senha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        JTF_ConfirmaSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("CONSUMIDOR ONLINE");

        jLabel8.setText("INFORMACOES DA CONTA");

        jLabel1.setText("NOME DE USUARIO");

        JTF_Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_NomeKeyTyped(evt);
            }
        });

        JTF_Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTF_EmailKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_EmailKeyTyped(evt);
            }
        });

        jLabel2.setText("EMAIL");

        JTF_ConfirmaEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_ConfirmaEmailKeyTyped(evt);
            }
        });

        jLabel3.setText("CONFIRMA EMAIL");

        JTF_Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_LoginKeyTyped(evt);
            }
        });

        jLabel4.setText("LOGIN");

        JTF_Senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_SenhaKeyTyped(evt);
            }
        });

        jLabel5.setText("SENHA");

        JTF_ConfirmaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTF_ConfirmaSenhaKeyTyped(evt);
            }
        });

        jLabel6.setText("CONFIRMA SENHA");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Voltar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTF_ConfirmaEmail)
                            .addComponent(JTF_Email)
                            .addComponent(JTF_Login)
                            .addComponent(JTF_Nome)
                            .addComponent(JTF_Senha)
                            .addComponent(JTF_ConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(177, 177, 177))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel7)
                .addGap(42, 42, 42)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(JTF_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_ConfirmaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTF_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTF_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JTF_ConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            Cliente cli = new Cliente();

            String nome = JTF_Nome.getText().toUpperCase();

            String login = JTF_Login.getText();

            final String email = JTF_Email.getText();

            String confirmaEmail = JTF_ConfirmaEmail.getText();

            String senha = "";

            String confirmaSenha = "";

            char[] repass = JTF_ConfirmaSenha.getPassword();

            for (int i = 0; i < repass.length; i++) {
                confirmaSenha += repass[i];

            }

            char[] pass = JTF_Senha.getPassword();

            for (int i = 0; i < pass.length; i++) {
                senha += pass[i];

            }

            if (checkMudou(nome, login, email, confirmaEmail, senha, confirmaSenha) == true) {

                JF_Tela_Principal tp = new JF_Tela_Principal(nome, senha, login, email, this.id);
                tp.setVisible(true);
                this.dispose();

            } else {

                if ((nome.isEmpty()) || (login.isEmpty()) || (email.isEmpty()) || (senha.isEmpty()) || (confirmaSenha.isEmpty())) {
                    JOptionPane.showMessageDialog(null, "Campo em branco");
                } else {
                    if (!(email.equals(confirmaEmail))) {
                        JOptionPane.showMessageDialog(null, "E-mails não compativeis");
                        JTF_ConfirmaEmail.setText("");
                    } else {
                        if (!(Pattern.matches("^[a-zA-Z0-9-.-_]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", JTF_Email.getText()))) {
                            JOptionPane.showMessageDialog(null, "Por favor, informe um e-mail valido", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            if (!(senha.equals(confirmaSenha))) {
                                JOptionPane.showMessageDialog(null, "Senhas não compativeis");

                            } else {
                                if (nome.length() > 230) {
                                    JOptionPane.showMessageDialog(null, "Campo de nome campo grande de mais", "Erro", JOptionPane.ERROR_MESSAGE);
                                } else {
                                    if (login.length() > 230) {
                                        JOptionPane.showMessageDialog(null, "Campo de login campo grande de mais", "Erro", JOptionPane.ERROR_MESSAGE);

                                    } else {
                                        if (login.length() < 5) {
                                            JOptionPane.showMessageDialog(null, "Campo de login não pode ter menos que 5 caracteres", "Erro", JOptionPane.ERROR_MESSAGE);
                                        } else {
                                            if (this.senha.length() > 230) {
                                                JOptionPane.showMessageDialog(null, "Campo de senha campo grande de mais", "Erro", JOptionPane.ERROR_MESSAGE);
                                            } else {
                                                if (senha.length() < 5) {
                                                    JOptionPane.showMessageDialog(null, "Campo de senha não pode ter menos que 5 caracteres", "Erro", JOptionPane.ERROR_MESSAGE);

                                                } else {

                                                    int opcao = 0;

                                                    Object[] options = {"Confirmar", "Cancelar"};

                                                    opcao = JOptionPane.showOptionDialog(null, "Clique Confirmar para continuar", "Informação",
                                                            JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

                                                    if (opcao == 0) {

                                                        jButton2.setEnabled(false);
                                                        jButton3.setEnabled(false);

                                                        if (!(email.equals(this.emailOk))) {
                                                            ClienteDAO cd = null;

                                                            cd = new ClienteDAO();
                                                            if (login.equals(loginOK)) {

                                                                if (cd.checkEmai(email) == null) {

                                                                    Random random = new Random();
                                                                    random.nextInt(9999);

                                                                    int okk = random.nextInt(9999);

                                                                    final String ok = "Codigo de confirmação de email";
                                                                    final String co = String.valueOf(okk);

                                                                    JF_TrocouEmail con = new JF_TrocouEmail(co, email, nome, login, senha, id);
                                                                    con.setVisible(true);

                                                                    new Thread() {

                                                                        @Override
                                                                        public void run() {

                                                                            EnviarEmail emailO = new EnviarEmail();
                                                                            emailO.enviarMail(email, ok, "O Codigo para confirmar alteração de email da sua conta no Consumidor Online: " + co);
                                                                        }
                                                                    }.start();
                                                                    JOptionPane.showMessageDialog(this, "Um email foi enviado para: " + email + "\nPode demorar alguns minutos para receber o email", "Menssagem do sistema", JOptionPane.INFORMATION_MESSAGE);
                                                                    this.dispose();
                                                                } else {
                                                                    JOptionPane.showMessageDialog(this, "Email ja cadastrado, por favor "
                                                                            + "registre um novo email!", "Erro", JOptionPane.ERROR_MESSAGE);
                                                                    jButton2.setEnabled(true);
                                                                    jButton3.setEnabled(true);
                                                                    JTF_ConfirmaEmail.setText("");
                                                                    JTF_Email.setText("");
                                                                }
                                                            } else {
                                                                if (cd.checkLoginL(login) != null) {
                                                                    JOptionPane.showMessageDialog(this, "Nome de login ja cadastrado, por favor registre um novo login!", "Erro", JOptionPane.ERROR_MESSAGE);
                                                                    JTF_Login.setText("");
                                                                    jButton2.setEnabled(true);
                                                                    jButton3.setEnabled(true);
                                                                } else {
                                                                    if (cd.checkEmai(email) == null) {

                                                                        Random random = new Random();
                                                                        random.nextInt(9999);

                                                                        int okk = random.nextInt(9999);

                                                                        final String ok = "Codigo de confirmação de email";
                                                                        final String co = String.valueOf(okk);

                                                                        JF_TrocouEmail con = new JF_TrocouEmail(co, email, nome, login, senha, id);
                                                                        con.setVisible(true);

                                                                        JOptionPane.showMessageDialog(this, "Um email foi enviado para: " + email + "\nPode demorar alguns minutos para receber o email", "Menssagem do sistema", JOptionPane.INFORMATION_MESSAGE);

                                                                       
                                                                        new Thread() {
                                                                            
                                                                            @Override
                                                                            public void run() {

                                                                                EnviarEmail emailO = new EnviarEmail();
                                                                                emailO.enviarMail(email, ok, "O Codigo para confirmação alteração de email da sua conta no Consumidor Online: " + co);
                                                                            }
                                                                        }.start();
                                                                       
////                                                                                
                                                                        

                                                                        this.dispose();
                                                                    } else {
                                                                        JOptionPane.showMessageDialog(this, "Email ja cadastrado, por favor "
                                                                                + "registre um novo email!", "Erro", JOptionPane.ERROR_MESSAGE);
                                                                        JTF_ConfirmaEmail.setText("");
                                                                        JTF_Email.setText("");
                                                                        jButton2.setEnabled(true);
                                                                        jButton3.setEnabled(true);
                                                                    }
                                                                }

                                                            }
                                                        } else {

                                                            cli.setId(this.id);
                                                            cli.setEmail(email);
                                                            cli.setLogin(login);
                                                            cli.setNome(nome);
                                                            cli.setSenha(senha);

                                                            ClienteDAO cd = null;

                                                            cd = new ClienteDAO();

                                                            if (login.equals(this.loginOK)) {

                                                                cd.update(cli);

                                                                JOptionPane.showMessageDialog(null, "Atualização efetuada com sucesso");

                                                                JTF_Email.setText("");
                                                                JTF_Nome.setText("");
                                                                JTF_ConfirmaEmail.setText("");
                                                                JTF_Login.setText("");
                                                                JTF_Senha.setText("");
                                                                JTF_ConfirmaSenha.setText("");

                                                                JF_Tela_Principal p = new JF_Tela_Principal(nome, senha, login, email, id);
                                                                p.setVisible(true);
                                                                this.dispose();
                                                            } else {
                                                                if (cd.checkLoginL(login) == null) {

                                                                    cd.update(cli);

                                                                    JOptionPane.showMessageDialog(null, "Atualização efetuada com sucesso");

                                                                    JTF_Email.setText("");
                                                                    JTF_Nome.setText("");
                                                                    JTF_ConfirmaEmail.setText("");
                                                                    JTF_Login.setText("");
                                                                    JTF_Senha.setText("");
                                                                    JTF_ConfirmaSenha.setText("");

                                                                    JF_Tela_Principal p = new JF_Tela_Principal(nome, senha, login, email, id);
                                                                    p.setVisible(true);
                                                                    this.dispose();
                                                                } else {
                                                                    JOptionPane.showMessageDialog(this, "Nome de login ja cadastrado, por favor registre um novo login!", "Erro", JOptionPane.ERROR_MESSAGE);
                                                                    JTF_Login.setText("");
                                                                    jButton2.setEnabled(true);
                                                                    jButton3.setEnabled(true);
                                                                }

                                                            }
                                                        }
                                                        if (opcao == 1) {

                                                        }
                                                        if (opcao == -1) {

                                                        }

                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

        } catch (SQLException ex) {
            Logger.getLogger(JF_AlterarInfoConta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (RuntimeException re) {
            Logger.getLogger(JF_AlterarInfoConta.class.getName()).log(Level.SEVERE, null, re);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JTF_Nome.setText(this.nome);
        JTF_Email.setText(this.email);
        JTF_ConfirmaEmail.setText(this.email);
        JTF_Login.setText(this.login);
        JTF_Senha.setText(this.senha);
        JTF_ConfirmaSenha.setText(this.senha);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        JF_Tela_Principal prin = new JF_Tela_Principal(this.nome, this.senha, this.login, this.email, this.id);
        prin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void JTF_NomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_NomeKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_JTF_NomeKeyTyped

    private void JTF_EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_EmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTF_EmailKeyPressed

    private void JTF_EmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_EmailKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_JTF_EmailKeyTyped

    private void JTF_ConfirmaEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_ConfirmaEmailKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_JTF_ConfirmaEmailKeyTyped

    private void JTF_LoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_LoginKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_JTF_LoginKeyTyped

    private void JTF_SenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_SenhaKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_JTF_SenhaKeyTyped

    private void JTF_ConfirmaSenhaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTF_ConfirmaSenhaKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_JTF_ConfirmaSenhaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AlterarInfoConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AlterarInfoConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AlterarInfoConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AlterarInfoConta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /* java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
         new JF_AlterarInfoConta().setVisible(true);
         }
         });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTF_ConfirmaEmail;
    private javax.swing.JPasswordField JTF_ConfirmaSenha;
    private javax.swing.JTextField JTF_Email;
    private javax.swing.JTextField JTF_Login;
    private javax.swing.JTextField JTF_Nome;
    private javax.swing.JPasswordField JTF_Senha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
